import Head from "next/head";
import HomeProducts from "../src/components/HomeProducts";
import HomeSlider from "../src/components/HomeSlider";
import Header from './../src/components/UI/Header/index';

export default function Home() {
    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header/>
            <HomeSlider/>
            <HomeProducts/>
        </div>
    );
}
