import Head from "next/head";
import HomeProducts from "../src/components/HomeProducts";
import HomeCategories from "../src/components/HomeCategories";
import HomeSlider from "../src/components/HomeSlider";
import Header from './../src/components/UI/Header/index';
import Newsletter from './../src/components/UI/Newsletter/index';
import Footer from './../src/components/UI/Footer/index';

export default function Home() {
    return (
        <div>
            <Head>
                <title>W Tailwind Store</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header/>
            <HomeSlider/>
            <HomeProducts/>
            <HomeCategories category={"electronics"} />
            <HomeCategories category={"jewelery"} />
            <Newsletter/>
            <Footer/>
        </div>
    );
}
